### ISSUE TITLE
Ability to zoom in and out of a process

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/spark-modeler#276]
If someone is building a large process, there is the potential for it to be too large to be easily navigated. This can happen on a process that uses multiple pool lanes, or with a browser on a smaller resolution screen.

**Comment by velkymx** [comment]
This is NOT approved for development

**Comment by velkymx** [comment]
@PMQABen wontfix - yet

**Comment by velkymx** [comment]
@chipit24 let's get the PR updated and if not completed, how much effort to complete it?

**Comment by chipit24** [comment]
@velkymx Merged `develop` into the now re-opened PR for this. Feature is complete and PR is up for review.
