### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#301]
We currently are translating the php / js version of bpm and we want the modeler to support this. Text strings needs to be added to a translation file that we can import into bpm to translation.

**Comment by chipit24** [comment]
@velkymx Got a draft PR up using `vue-i18n`: https://github.com/ProcessMaker/modeler/pull/303.

The translations used in the PR (currently just two, for testing) are exported as part of the `build-bundle` script, and can be imported elsewhere. Is this how you are expecting it to work?

**Comment by velkymx** [comment]
https://github.com/ProcessMaker/laravel-i18next

https://github.com/panter/vue-i18next

**Comment by chipit24** [comment]
I didn't find any examples of how you're currently implementing i18n to help with https://github.com/ProcessMaker/modeler/pull/312. The [`vue-i18next`](https://github.com/panter/vue-i18next) library has to be installed as a plugin, which isn't ideal for a package that is bundled as a "standalone" library (`Vue` is externalized).

I think the best approach would be to set it up only using `i18next`. That way, each component which expects translations can accept a `translations` prop:

```js
// Modeler.vue
...
props: ['translations'],
created() {
  if (this.translations) {
    i18next.init({
      lng: 'en', /* Possibly also passed as a prop */
      fallbackLng: 'en',
      resources: this.translations,
    });
  }
}
...
```

Integrating it with VueX would be even better. I'll explore this solution tomrrow and update the related PR.

**Comment by velkymx** [comment]
I'd like to follow the patterns put into place by the core team here:
https://github.com/ProcessMaker/bpm/issues/1617
