### ISSUE TITLE
422 error when using gates

### ISSUE THREAD

**Issue by ZLTM** [ProcessMaker/spark-modeler#314]
*_Steps to Reproduce:_*
 go to a process
 make a flow that includes gates
 press the validate BPMN button to confirm there are no errors
 save the process

*_Current Behavior:_*
 The message ‘The bpm definition is not valid’ appears, the process won't save.
 A 422 error appears on the console

*_Expected Behavior:_*
 The process saves normally if the BPMN validation ends successfully

![error422](https://user-images.githubusercontent.com/7957742/55654650-fefeeb00-57bf-11e9-9a98-363ab5b893f3.png)

**Comment by PMQABen** [comment]
Video of the error:
[422_error_when_using_gates.mp4.zip](https://github.com/ProcessMaker/modeler/files/3049560/422_error_when_using_gates.mp4.zip)

**Comment by velkymx** [comment]
@ZLTM can you include the BPMN or export the process for us to test?

**Comment by ZLTM** [comment]
@velkymx as the process can't be saved it can't be exported, however a simple process using 2 parallel gates will work, something like:
![GateBug](https://user-images.githubusercontent.com/7957742/55890520-d3458180-5b80-11e9-9e31-3c447230803b.png)

The first gate is Diverging, the second one is converging, no other special configuration

**Comment by tuantruong625** [comment]
@ZLTM We noticed you are using a different version of modeler. We could not reproduce this bug using version 0.7.2 of the modeler.

**Comment by velkymx** [comment]
@PMQABen can you try to reproduce this issue in the latest version on develop?

**Comment by ZLTM** [comment]
Thanks @tuantruong625 !
 I confirm the bug is fixed in the last version of the modeler.
