### ISSUE TITLE
MS Edge - Controls Don't Show

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#321]
While using Microsoft Edge, dragging BPMN controls onto the modeler does not show the BPMN control icon.

**Comment by chipit24** [comment]
Libraries that use or warp the HTML Drag and Drop API don't seem to work well in both MS Edge and Safari. I think the cleanest approach would be to use a custom drag/drag library, like https://github.com/Shopify/draggable. `draggable` seems to work well in all cases.

**Comment by velkymx** [comment]
I reached out to the product team to find out how important this issue is.
