### ISSUE TITLE
Changing the Identifier/"ProcessId" 422

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#323]
Changing the Identifier/"ProcessId" to numbers throws a 422 (Unprocessable Entity) error, and the user cannot make any further changes to the Process because it will no longer save. Even changing the Identifier back to "ProcessId" does not allow it to save.	

1. Create New Process
1. Change Process Identifier from "ProcessId" to any string of numbers
1. Press save twice

**Comment by tuantruong625** [comment]
@velkymx This issue was brought up in https://github.com/ProcessMaker/spark-modeler/issues/203.

> It does have some blurb about QName on page 477 (507 in PDF):
> 
> The BPMN XSD utilizes IDREFs wherever possible and resorts to QName only when references can span files. In both situations however, the reference is still based on IDs.
> 
> Here, QNames can't have spaces or start with numbers. When testing this in Camunda, it throws an error saying "Id must be a valid QName".

Do you want to enforce these rules as an bpmn-lint rule? This won't fix the issue as it is  back-end issue. @caleeli

**Comment by caleeli** [comment]
I would suggest to add a validation for Ids, that must be a valid QName.
