### ISSUE TITLE
Unsupported Elements

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#357]
If a BPMN file contains an unsupported element, we'd like throw an error that the BPMN contains unsupported elements.

**Comment by velkymx** [comment]
@chipit24 @ssshake this is ok for now, but we should discuss changes like this before implementation. For example, we show alerts at the top of the page, not the bottom - and it should show in the linter. I'm going to reopen the issue.

**Comment by chipit24** [comment]
@velkymx This seems to have already been fixed:

<img width="1440" alt="Screen Shot 2019-06-04 at 10 14 22 AM" src="https://user-images.githubusercontent.com/7561061/58886439-e4f36300-86b1-11e9-97ab-9490b4896f1f.png">

And it's using the "built-in" alert system:
https://github.com/ProcessMaker/spark-modeler/blob/8c9990a89bbd8778fb851ff44f69b9fd39c19a66/src/components/Modeler.vue#L461

Though the import process on spark has been significantly changed so I'm not sure how relevant this is anymore. When I try to import the same process that produces the warnings in standalone, I get a generic error in spark instead:

<img width="1135" alt="Screen Shot 2019-06-04 at 10 22 29 AM" src="https://user-images.githubusercontent.com/7561061/58887028-d22d5e00-86b2-11e9-8539-b2dea757c39c.png">

**Comment by velkymx** [comment]
When I import a BMPN with an issue. Current behavior is that it crashes and becomes unresponsive. You also cannot save the BPMN.

**Comment by velkymx** [comment]
https://www.dropbox.com/s/qjwdum8avi04k92/import-unsupport-lockup.mov?dl=0
