### ISSUE TITLE
Invalida BPMN property "global" in task

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/spark-modeler#366]
The following property is not a valid BPMN property:

![image](https://user-images.githubusercontent.com/8028650/57535318-fa25dd80-730f-11e9-808a-2e39f075ec9a.png)

Causing this error en BE validation:
```
 Element '{http://www.omg.org/spec/BPMN/20100524/MODEL}task', attribute 'global': The attribute 'global' is not allowed.
```

**Comment by velkymx** [comment]
Declare as global needs to be removed.

**Comment by ssshake** [comment]
@velkymx  This was removed in modeler but I may not have realized this ticket was lingering. I will retest and confirm.

**Comment by ssshake** [comment]
this is confirmed as fixed on develop
