### ISSUE TITLE
Bug in Search Control

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/spark-modeler#367]
The correct control is not loaded after using the controls filter

![SearchScreenBuilder](https://user-images.githubusercontent.com/8028650/57538631-d6b26100-7316-11e9-9a0f-9a7425dcca0b.gif)

**Comment by chipit24** [comment]
@caleeli This should be moved to the `spark-screen-builder` repository.

**Comment by caleeli** [comment]
this issue was moved to spark-screen-builder
https://github.com/ProcessMaker/spark-screen-builder/issues/179
