### ISSUE TITLE
Move DueIn & User Assignment into Configuration

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/spark-modeler#371]
**Steps to reproduce**
- Drag a task
- Click on task
- `Due In` & `Users` form elements are not aligned with the other form elements

<img width="632" alt="Screen Shot 2019-05-15 at 1 58 14 PM" src="https://user-images.githubusercontent.com/26545455/57797991-a8b78d00-7719-11e9-84c0-1308ccce2314.png">

**Comment by chipit24** [comment]
Fixed in https://github.com/ProcessMaker/spark-modeler/pull/373.
