### ISSUE TITLE
The crown icons are jumping around

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/spark-modeler#383]
![image](https://user-images.githubusercontent.com/1675868/57802722-9bec6680-7724-11e9-9c38-4881883b1510.png)

**Comment by tuantruong625** [comment]
@velkymx 

The crown position bug is fixed, but I made the crown positioning anchored to the top right of the element. Similar to how it is done is Camuda.

**Current Implementation** 
 https://drive.google.com/open?id=1U1hkUyK1qVpEbryABl1CeAL_TzFTFu9I

Do we want to anchor the crown to the middle-right of the element or move forward ?

**Camunda**
<img width="827" alt="Screen Shot 2019-05-30 at 4 01 32 PM" src="https://user-images.githubusercontent.com/26545455/58660885-7c446900-82f4-11e9-8811-b476a2135cab.png">

**Spark Modeler**
<img width="1107" alt="Screen Shot 2019-05-30 at 4 01 04 PM" src="https://user-images.githubusercontent.com/26545455/58660907-88c8c180-82f4-11e9-92b7-b51f650ab1ac.png">

**Comment by velkymx** [comment]
This looks good to me...
