### ISSUE TITLE
Wrong timer property for PT1M 

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/spark-modeler#392]
We're not doing ISO8601 properly. That should be a 1 minute delay, but the process is seeing it as a 1 month delay.

![image](https://user-images.githubusercontent.com/8028650/57945802-d848cf80-78a8-11e9-8a94-d2549662d144.png)

**Comment by chipit24** [comment]
@caleeli I don't see any active branches for this and you self-assigned 10 days ago. I'm going to take this over and get a PR up.

**Comment by chipit24** [comment]
The modeler has no problem getting and setting the correct value for 1 month delay for the intermediate timer event: `P1M`. The issue arrises when trying to import an event that already has `PT1M` set. An option to handle minutes was never implemented (the dropdown only shows options for hour, day, and month).

I'll add the option to handle minutes.

**Comment by chipit24** [comment]
Relevant notes from [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Durations):

> The capital letters P, Y, M, W, D, T, H, M, and S are designators for each of the date and time elements and are not replaced.
> 
> P is the duration designator (for period) placed at the start of the duration representation.
> Y is the year designator that follows the value for the number of years.
> M is the month designator that follows the value for the number of months.
> W is the week designator that follows the value for the number of weeks.
> D is the day designator that follows the value for the number of days.
> T is the time designator that precedes the time components of the representation.
> H is the hour designator that follows the value for the number of hours.
> M is the minute designator that follows the value for the number of minutes.
> S is the second designator that follows the value for the number of seconds.

And it's possible to have a combination of the cases above, as the next sentence in the linked Wikipedia article mentions:

> For example, "P3Y6M4DT12H30M5S" represents a duration of "three years, six months, four days, twelve hours, thirty minutes, and five seconds".

@velkymx @caleeli  Do we want to handle all possible combinations? Currently, it's only possible to set a single value for one of minutes, hours, days, or months.
