### ISSUE TITLE
Validation Not Clearing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#397]
Creating and deleting an element with validation errors does not remove the validation errors

![image](https://user-images.githubusercontent.com/535300/58179446-0fc6cb80-7c5d-11e9-9cca-5b60eebca202.png)

**Comment by chipit24** [comment]
I can't reproduce this on the latest `develop` branch in `spark-modeler` or `spark`.

Looking at the screenshot, the errors listed are with the process itself, **not** with any non-existent element, which to me seems like intended behaviour. While testing this, I did notice that validation errors weren't updating right after pressing undo / redo–I'll create a separate issue for that.

**Comment by velkymx** [comment]
OK Let's circle back if QA reports again
