### ISSUE TITLE
Error in event handler: modeler-init

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#402]
In modeler i'm getting `Error in event handler for "modeler-init": "TypeError: Cannot read property 'implementation' of undefined"` somewhere in the script task control neighborhood since no other controls are loading load after it

**Comment by chipit24** [comment]
This issue is fixed in latest `develop` branch of `spark-modeler`. I noticed the error on a build of the latest `develop` on `spark`, but when I `npm link`'ed the latest `spark-modeler` `develop` branch, the error was gone.
