### ISSUE TITLE
Validation Error using Intermediate Message Catch Event 

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/spark-modeler#407]
When create an Intermediate Message Catch Event, its <messageEventDefinition> is being saved/created with invalid properties that is causing and validation error on saving the xml diagram.

If the Message Event Identifier is empty:
![image](https://user-images.githubusercontent.com/8028650/58570642-5e003f80-8206-11e9-85cd-d84ff207ca3e.png)

The attribute **variableName** is not defined in the XSD nor moddle extension, the defined attribute in the PRD and in the latest version of the XSD and the moddle extension is "**dataName**" so using variableName is causing an validation error here:
![image](https://user-images.githubusercontent.com/8028650/58571553-f77c2100-8207-11e9-83c8-8911e41aa650.png)

[PM4-IntermediateMessageCatchEvent-PRD-290519-1556.pdf](https://github.com/ProcessMaker/spark-modeler/files/3233338/PM4-IntermediateMessageCatchEvent-PRD-290519-1556.pdf)

**Comment by tuantruong625** [comment]
@caleeli @velkymx 

Data name was renamed to variable name.
Issue: https://github.com/ProcessMaker/spark-modeler/issues/356
PR: https://github.com/ProcessMaker/spark-modeler/pull/360

I believe this change also needs to happen in `processmaker-bpmn-moddle`.

**Comment by caleeli** [comment]
Could be good to have an initial default value for the "Message Event Identifier" that could be "**message**"
